"""Utility for summarizing documents using an LLM."""

import re
from datetime import datetime
from pathlib import Path
from snyk_ai import Model

_PROMPT_DOC_SUMMARY = """
Summarize the following document in a single paragraph:
---
{content}
---
Provide a concise summary that captures the key points.
"""


def summarize_document(document_path: Path, llm: Model, persist: bool = True) -> Path:
    """
    Summarize a document using an LLM and save the summary to a file.

    Saves summary to: <parent>/.summaries/<doc_name>-summary-<model>-<timestamp>.txt
    Also creates <doc_name>-summary.txt symlink to created summary file.

    Args:
        document_path: Path to the document to summarize.
        llm: LLM model instance to use for summarization.

    Returns:
        Path to the generated summary file.
    """
    content = document_path.read_text(encoding="utf-8")
    prompt = _PROMPT_DOC_SUMMARY.format(content=content)

    summary = llm.generate(prompt)

    # Build summary filename: <doc_name>-summary-<model_name>-<timestamp>.txt
    doc_name = document_path.stem
    model_name = llm.name.replace(":", "_")
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    summary_filename = f"{doc_name}-summary-{model_name}-{timestamp}.txt"

    # save to .summaries/ subdirectory
    summaries_dir = document_path.parent / ".summaries"
    summaries_dir.mkdir(exist_ok=True)
    summary_path = summaries_dir / summary_filename
    summary_path.write_text(summary, encoding="utf-8")

    # create/update symlink in parent directory
    symlink_path = document_path.parent / f"{doc_name}-summary.txt"
    if symlink_path.is_symlink() or symlink_path.exists():
        symlink_path.unlink()
    symlink_path.symlink_to(f"summaries/{summary_filename}")

    return summary_path


_PROMPT_CODE_SUMMARY = """
Summarize the following code in exactly one sentence:
```
{code}
```
Respond with only a single sentence summary, no additional text.
"""

# markdown code blocks: ```lang\n...lines...\n```
_CODE_BLOCK_PATTERN = re.compile(r"^```\w*\n?(.*?)\n?```$", re.DOTALL)


def summarize_code_snippet(code_snippet: str, llm: Model) -> str:
    """
    Summarize a code snippet using an LLM.

    Args:
        code_snippet: The code to summarize. May be wrapped in markdown
            code fences (```), which will be stripped before processing.
        llm: LLM model instance to use for summarization.

    Returns:
        Summary of what the code does generated by the provided LLM.
    """
    if not code_snippet or not (code := code_snippet.strip()):
        raise ValueError("Empty code snippet")

    # strip markdown code fences if present
    if match := _CODE_BLOCK_PATTERN.match(code):
        code = match.group(1).strip()

    if not code:
        raise ValueError("empty code snippet")

    prompt = _PROMPT_CODE_SUMMARY.format(code=code)
    return llm.generate(prompt)
